import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export const pdfService = {
  /**
   * Generate Route Map & Stop Schedule PDF Document
   */
  async generateRoutePdf(routeData) {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 800]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();

    // Header Title Banner
    page.drawRectangle({
      x: 0,
      y: height - 100,
      width,
      height: 100,
      color: rgb(0.08, 0.35, 0.65), // GLOW Navy Blue
    });

    page.drawText("GLOW CAMPUS TRANSIT SYSTEM", {
      x: 30,
      y: height - 40,
      size: 18,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText(`Official Route Schedule & Corridor Map — ${routeData.name || "Route Corridor"}`, {
      x: 30,
      y: height - 65,
      size: 12,
      font,
      color: rgb(0.9, 0.95, 1),
    });

    // Route Specification Card
    let y = height - 130;
    page.drawText("CORRIDOR SPECIFICATIONS", { x: 30, y, size: 14, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
    y -= 20;
    page.drawText(`Origin: ${routeData.origin || "Terminal Station"}`, { x: 30, y, size: 11, font });
    page.drawText(`Destination: ${routeData.destination || "Main Campus"}`, { x: 300, y, size: 11, font });
    y -= 18;
    page.drawText(`Total Distance: ${routeData.distanceKm || 14.5} km`, { x: 30, y, size: 11, font });
    page.drawText(`Est. Travel Time: ${routeData.durationMin || 35} mins`, { x: 300, y, size: 11, font });

    // Table Header
    y -= 40;
    page.drawRectangle({ x: 30, y: y - 5, width: 540, height: 25, color: rgb(0.92, 0.94, 0.98) });
    page.drawText("#", { x: 40, y, size: 11, font: fontBold });
    page.drawText("Bus Stop Name", { x: 80, y, size: 11, font: fontBold });
    page.drawText("ETA Offset", { x: 320, y, size: 11, font: fontBold });
    page.drawText("Coordinates", { x: 440, y, size: 11, font: fontBold });

    // Table Rows
    const stops = routeData.stops || [
      { name: "Terminal Station", etaOffsetMin: 0, lat: 23.102, lng: 72.585 },
      { name: "Crossroads Stop", etaOffsetMin: 12, lat: 23.091, lng: 72.591 },
      { name: "Campus Gate 1", etaOffsetMin: 35, lat: 23.078, lng: 72.592 },
    ];

    stops.forEach((stop, index) => {
      y -= 25;
      page.drawText(`${index + 1}`, { x: 40, y, size: 10, font });
      page.drawText(stop.name, { x: 80, y, size: 10, font });
      page.drawText(`+${stop.etaOffsetMin || index * 10} min`, { x: 320, y, size: 10, font });
      page.drawText(`${stop.lat || 23.08}, ${stop.lng || 72.58}`, { x: 440, y, size: 10, font });
    });

    // Footer
    page.drawText("Certified document generated by GLOW Campus Transit API Engine.", {
      x: 30,
      y: 30,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    return await pdfDoc.save();
  },

  /**
   * Generate Timetable Schedule PDF Document
   */
  async generateSchedulePdf(studentData, scheduleType = "regular") {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 750]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();

    page.drawRectangle({
      x: 0,
      y: height - 90,
      width,
      height: 90,
      color: rgb(0.1, 0.45, 0.35), // Teal theme for schedule
    });

    page.drawText("GLOW TRANSIT — ACADEMIC TIMETABLE", {
      x: 30,
      y: height - 40,
      size: 18,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText(`Official Shift & Transit Schedule (${scheduleType.toUpperCase()} MODE)`, {
      x: 30,
      y: height - 65,
      size: 12,
      font,
      color: rgb(0.9, 0.98, 0.95),
    });

    let y = height - 120;
    page.drawText(`Student: ${studentData?.name || "Rahul Sharma"} (${studentData?.id || "UNI20260125"})`, {
      x: 30,
      y,
      size: 11,
      font: fontBold,
    });
    page.drawText(`Route: ${studentData?.routeName || "Route R-04 (SG Highway)"}`, { x: 320, y, size: 11, font });

    y -= 35;
    page.drawRectangle({ x: 30, y: y - 5, width: 540, height: 25, color: rgb(0.9, 0.95, 0.93) });
    page.drawText("Shift / Service", { x: 40, y, size: 11, font: fontBold });
    page.drawText("Departure Time", { x: 200, y, size: 11, font: fontBold });
    page.drawText("Corridor", { x: 340, y, size: 11, font: fontBold });
    page.drawText("Status", { x: 480, y, size: 11, font: fontBold });

    const rows = [
      { shift: "Morning Pickup", time: "07:30 AM", route: "R-04 SG Highway", status: "On Time" },
      { shift: "Mid-Day Campus Link", time: "01:15 PM", route: "R-04 Shuttle", status: "Scheduled" },
      { shift: "Evening Return", time: "05:15 PM", route: "R-04 SG Highway", status: "Scheduled" },
    ];

    rows.forEach((row) => {
      y -= 25;
      page.drawText(row.shift, { x: 40, y, size: 10, font });
      page.drawText(row.time, { x: 200, y, size: 10, font });
      page.drawText(row.route, { x: 340, y, size: 10, font });
      page.drawText(row.status, { x: 480, y, size: 10, font });
    });

    return await pdfDoc.save();
  },

  /**
   * Generate Transport Pass PDF Document with HMAC QR Payload
   */
  async generatePassPdf(passData) {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([500, 650]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();

    // Pass Border Frame
    page.drawRectangle({
      x: 20,
      y: 20,
      width: width - 40,
      height: height - 40,
      borderWidth: 2,
      borderColor: rgb(0.08, 0.35, 0.65),
      color: rgb(0.98, 0.99, 1),
    });

    // Pass Banner Header
    page.drawRectangle({
      x: 20,
      y: height - 110,
      width: width - 40,
      height: 90,
      color: rgb(0.08, 0.35, 0.65),
    });

    page.drawText("DIGITAL TRANSPORT PASS", {
      x: 40,
      y: height - 55,
      size: 20,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText("GLOW CAMPUS TRANSIT SYSTEM — OFFICIAL CREDENTIAL", {
      x: 40,
      y: height - 80,
      size: 10,
      font,
      color: rgb(0.85, 0.92, 1),
    });

    let y = height - 150;
    page.drawText(`PASS ID: ${passData?.passCode || "PASS-STU-2026-0125"}`, { x: 40, y, size: 14, font: fontBold });
    y -= 25;
    page.drawText(`Student Name: ${passData?.studentName || "Rahul Sharma"}`, { x: 40, y, size: 12, font });
    y -= 20;
    page.drawText(`Enrollment ID: ${passData?.studentId || "UNI20260125"}`, { x: 40, y, size: 11, font });
    y -= 20;
    page.drawText(`Route Corridor: ${passData?.routeName || "Route R-04 (SG Highway)"}`, { x: 40, y, size: 11, font });
    y -= 20;
    page.drawText(`Distance Zone: ${passData?.zone || "Zone B"}`, { x: 40, y, size: 11, font });
    y -= 20;
    page.drawText(`Pass Status: ${passData?.status || "ACTIVE"}`, { x: 40, y, size: 11, font: fontBold });
    y -= 20;
    page.drawText(`Valid Until: ${passData?.expiryDate || "31 May 2027"}`, { x: 40, y, size: 11, font });

    // HMAC Signature Display Box
    y -= 40;
    page.drawRectangle({ x: 40, y: y - 10, width: width - 80, height: 40, color: rgb(0.93, 0.94, 0.97) });
    page.drawText("HMAC SECURITY PAYLOAD SIGNATURE:", { x: 50, y: y + 12, size: 8, font: fontBold });
    page.drawText(passData?.signedPayload || "HMAC_SIG_SHA256_GLOW_PASS_2026_VALID", {
      x: 50,
      y: y - 2,
      size: 9,
      font,
      color: rgb(0.2, 0.2, 0.6),
    });

    return await pdfDoc.save();
  },
};
